name: Agentic AI Digest
on:
  schedule:
    - cron: '7 3 * * *'   # daily 03:07 UTC
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          python -m src.main
      - name: Commit digest
        run: |
          git config user.name "agentic-bot"
          git config user.email "actions@github"
          git add docs/index.html docs/data.json
          git commit -m "update digest" || echo "no changes"
          git push
