name: Agentic AI Digest

on:
  workflow_dispatch: {}
  schedule:
    - cron: "7 3 * * *"  # 03:07 UTC daily

permissions:
  contents: write  # needed to push generated files

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate digest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TRACKER_DEBUG: "0"   # set "1" if you want extra logs
        run: |
          python -m src.main
          test -f docs/index.html
          test -f docs/data.json

      - name: Commit digest
        run: |
          git config user.name "agentic-bot"
          git config user.email "actions@github"
          git add docs/index.html docs/data.json
          git commit -m "update digest" || echo "no changes"
          git push
